apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db  # Assure-toi que ce label correspond à celui de ton déploiement "vote"
  ports:
    - protocol: TCP
      port: 5432  # Le port sur lequel le service est exposé
      targetPort: 5432  # Le port interne du conteneur où l'application écoute
  storageClassName: "standard-rwo"