services:
  redis:
    image: "redis:alpine"
    container_name: redis
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: ["CMD", "sh", "/healthchecks/redis.sh"]
      interval: 5s
      timeout: 5s
      retries: 2
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres # used in result/server.js
      POSTGRES_PASSWORD: postgres # same
      POSTGRES_DB: postgres # same
    volumes:
      - db-data:/var/lib/postgresql/data  # Persistent database storage
      #- ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql  # Ajout du script SQL
      - ./healthchecks:/healthchecks      # Health check scripts
    healthcheck:
      test: ["CMD", "sh", "/healthchecks/postgres.sh"]
      interval: 5s
      timeout: 5s
      retries: 2
    ports:
      - "5432:5432"

  vote1:
      image: europe-west9-docker.pkg.dev/white-fiber-453513-e9/voting-image/vote1
      build: ./vote  # Construire l'image à partir du Dockerfile dans ./vote
      container_name: vote1
      depends_on:
        - redis
          #condition: service_healthy
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      ports:
      - "5000:5000"
  vote2:
      image: europe-west9-docker.pkg.dev/white-fiber-453513-e9/voting-image/vote2
      build: ./vote  # Construire l'image à partir du Dockerfile dans ./vote
      container_name: vote2
      depends_on:
        - redis
          #condition: service_healthy
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      ports:
      - "5001:5000"

  vote3:
      image: europe-west9-docker.pkg.dev/white-fiber-453513-e9/voting-image/vote3
      build: ./vote  # Construire l'image à partir du Dockerfile dans ./vote
      container_name: vote3
      depends_on:
        - redis
          #condition: service_healthy
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      ports:
      - "5002:5000"

  result:
    image: europe-west9-docker.pkg.dev/white-fiber-453513-e9/voting-image/result
    build: ./result  # Construire l'image à partir du Dockerfile dans ./vote
    container_name: result
    depends_on:
      - db
        #condition: service_healthy
    environment:
      - db_HOST=db
      - db_PORT=5432
    ports:
    - "3001:3000"

  nginx:
    image: europe-west9-docker.pkg.dev/white-fiber-453513-e9/voting-image/nginx
    build: ./nginx  # Construire l'image à partir du Dockerfile dans ./nginx
    container_name: nginx
    depends_on:
      - vote1
      - vote2
      - vote3
    ports:
      - "80:80"  # Expose le port 80 du conteneur pour le service nginx
    

  worker:
    image: europe-west9-docker.pkg.dev/white-fiber-453513-e9/voting-image/worker
    build: ./worker
    container_name: worker
    depends_on:
      - redis
      - db
    ports:
    - "8000:8000"

  seed:
    image: europe-west9-docker.pkg.dev/white-fiber-453513-e9/voting-image/seed
    build: ./seed-data  
    container_name: seed
    #depends_on:
    #  - nginx  # Dépendance sur nginx, s'assure que nginx est démarré avant seed
    #environment:
    #  - NGINX_HOST=nginx
    #  - NGINX_PORT = 80  
    ports:
      - "8080:8080"  

volumes:
  db-data: 

