services:
  redis:
    image: "redis:alpine"
    container_name: redis
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: ["CMD", "sh", "/healthchecks/redis.sh"]
      interval: 5s
      timeout: 5s
      retries: 2
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres # used in result/server.js
      POSTGRES_PASSWORD: postgres # same
      POSTGRES_DB: postgres # same
    volumes:
      - db-data:/var/lib/postgresql/data  # Persistent database storage
      - ./healthchecks:/healthchecks      # Health check scripts
    healthcheck:
      test: ["CMD", "sh", "/healthchecks/postgres.sh"]
      interval: 5s
      timeout: 5s
      retries: 2
    ports:
      - "5432:5432"
    
volumes:
  db-data: 
