apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis  # Assure-toi que ce label correspond à celui de ton déploiement "vote"
  ports:
    - protocol: TCP
      port: 6379 # Le port sur lequel le service est exposé
      targetPort: 6379  # Le port interne du conteneur où l'application écoute