apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: LoadBalancer
  selector:
    app: result  # Assure-toi que ce label correspond à celui de ton déploiement "result"
  ports:
    - protocol: TCP
      port: 3000  # Le port sur lequel le service est exposé
      targetPort: 3000  # Le port interne du conteneur où l'application écoute