apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1  
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: europe-west9-docker.pkg.dev/tuto-jihene/voting-image/worker:latest  
        env:
        - name: REDIS_HOST
          value: "redis"  # Connexion au service Redis
        - name: DB_HOST
          value: "db"  # Connexion au service PostgreSQL
